/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.27
</auto-generated>
------------------------------------------------------------------------------ */

using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;

namespace SitefinityWebApp.Mvc.Models
{
	public class CompanyModel
	{
		public string Name { get; set; }
		public string Email { get; set; }
		public string Website { get; set; }
		public string urlName { get; set; }
        public string urlLogo { get; set; }
    }
}