/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.27
</auto-generated>
------------------------------------------------------------------------------ */

using SitefinityWebApp.Mvc.Models;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Personalization;

namespace SitefinityWebApp.Mvc.Controllers
{
	[ControllerToolboxItem(Name = "AssetssAdminLTE_MVC", Title = "AssetssAdminLTE", SectionName = "CustomWidgets")]
	public class AssetssAdminLTEController : Controller, IPersonalizable
	{
		// GET: AssetssAdminLTE
		public ActionResult Index()
		{
			return View("Index");
		}
		
        protected override void HandleUnknownAction(string actionName)
        {
            this.ActionInvoker.InvokeAction(this.ControllerContext, "Index");
        }
	}
}