/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.27
</auto-generated>
------------------------------------------------------------------------------ */

using SitefinityWebApp.Mvc.Models;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Personalization;

namespace SitefinityWebApp.Mvc.Controllers
{
	[ControllerToolboxItem(Name = "Navbar_MVC", Title = "Navbar", SectionName = "AdminLTEWidgets")]
	public class NavbarController : Controller, IPersonalizable
	{
		// GET: Navbar
		public ActionResult Index()
		{
			var model = new NavbarModel();
			model.Message = this.Message;
			return View("Index", model);
		}
		
        protected override void HandleUnknownAction(string actionName)
        {
            this.ActionInvoker.InvokeAction(this.ControllerContext, "Index");
        }

		public string Message { get; set; }
	}
}